"""drop unused patterns table

Revision ID: 56822ee323a9
Revises: c5b08cb93b61
Create Date: 2026-08-14 20:36:53.287439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56822ee323a9'
down_revision: Union[str, Sequence[str], None] = 'c5b08cb93b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patterns_match_id'), table_name='patterns')
    op.drop_table('patterns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patterns',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('patterns_match_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patterns_pkey'))
    )
    op.create_index(op.f('ix_patterns_match_id'), 'patterns', ['match_id'], unique=False)
    # ### end Alembic commands ###
