"""create initial schema

Revision ID: 6c76a60e67ce
Revises: 
Create Date: 2026-08-14 16:52:24.460122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c76a60e67ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferred_sport', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rallies', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Integer(), nullable=True),
    sa.Column('video_storage_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('match_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('individual_pct', sa.Integer(), nullable=True),
    sa.Column('collective_pct', sa.Integer(), nullable=True),
    sa.Column('tactical_pct', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_match_id'), 'analyses', ['match_id'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('match_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('match_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_match_id'), 'patterns', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patterns_match_id'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_analyses_match_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
