"""add skills, highlights, insights to matches

Revision ID: ad6a9c331e40
Revises: 6c76a60e67ce
Create Date: 2026-08-14 19:45:21.133645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6a9c331e40'
down_revision: Union[str, Sequence[str], None] = '6c76a60e67ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('highlights', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'insights')
    op.drop_column('matches', 'highlights')
    op.drop_column('matches', 'skills')
    # ### end Alembic commands ###
