"""add patterns_summary to matches

Revision ID: c5b08cb93b61
Revises: ad6a9c331e40
Create Date: 2026-08-14 20:05:30.261799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b08cb93b61'
down_revision: Union[str, Sequence[str], None] = 'ad6a9c331e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('patterns_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'patterns_summary')
    # ### end Alembic commands ###
